# Generated by Django 4.2.4 on 2023-08-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_package_alter_banner_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
    ]
