# Generated by Django 4.2.4 on 2023-08-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='highlight_status',
            field=models.BooleanField(default=False),
        ),
    ]
