# Generated by Django 4.2.4 on 2023-08-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_packagefeatures_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagefeatures',
            name='package',
        ),
        migrations.AddField(
            model_name='packagefeatures',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.package'),
        ),
    ]
