# Generated by Django 4.2.4 on 2023-08-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_packagefeatures_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_member',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
