# Generated by Django 4.2.4 on 2023-08-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_package_max_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='max_member',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
