# Generated by Django 4.2.4 on 2023-08-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_packagefeatures_options_packagediscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagediscount',
            name='package',
        ),
        migrations.AddField(
            model_name='packagediscount',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.package'),
        ),
    ]
