# Generated by Django 4.2.4 on 2023-09-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_subscription_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(upload_to='site_logo/')),
                ('site_title', models.CharField(max_length=200)),
                ('site_description', models.TextField()),
                ('copyright_text', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_address', models.CharField(max_length=50)),
            ],
        ),
    ]
