# Generated by Django 4.2.4 on 2023-09-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_subscription_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Slider'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='button_url',
            field=models.TextField(default='', verbose_name=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='Empty', max_length=200),
            preserve_default=False,
        ),
    ]
