# Generated by Django 4.2.4 on 2023-09-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_banner_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
